stem_dir: "data/musdb/train"
speech_dir: "data/LibriSpeech/dev-clean"
noise_dir: "data/noise/sound-bible"
trans_dir : "data/LibriSpeech/dev-clean"
output_dir: "processed_data_1_clean_10"  # Base directory for processed data
commonvoice_clips_dir : "data/cv-corpus-17.0-delta-2024-03-15/en/clips"
min_smr : -3                       # min Speech to Music Ratio(SMR)(unit: dB)
max_smr : 6                       # max Speech to Music Ratio(SMR)(unit: dB)
min_snr: 0                       # min Signal to Noise Ratio(SNR)(unit: dB)
max_snr: 5                       # max Signal to Noise Ratio(SNR)(unit: dB)
                              
                              # SNR = 20 dB: The signal power is 100 times greater than the noise power.
                              # SNR = 0 dB: The signal and noise have equal power.
                              # SNR < 0 dB: The noise power is greater than the signal power.

seed : 42                    # Random seed for data reproduction
